worker_processes  1;

events {
    worker_connections 1024;
}

http {

    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    upstream catalogue {
        server catalogue:8080;
    }

    upstream user {
        server user:8080;
    }

    upstream cart {
        server cart:8080;
    }

    upstream shipping {
        server shipping:8080;
    }

    upstream payment {
        server payment:8080;
    }

    server {
        listen 80;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /catalogue/ {
            proxy_pass http://catalogue/;
        }

        location /user/ {
            proxy_pass http://user/;
        }

        location /cart/ {
            proxy_pass http://cart/;
        }

        location /shipping/ {
            proxy_pass http://shipping/;
        }

        location /payment/ {
            proxy_pass http://payment/;
        }
    }
}