version: '3.9'

services:
  catalogue:
    build: ./catalogue
    image: pavankumarsri/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build: ./user
    image: pavankumarsri/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pavankumarsri/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user

  mongodb:
    build: ./mongodb
    image: pavankumarsri/mongodb:1.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop

    