FROM maven:3.9.14 AS build

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar shipping.jar 

EXPOSE 8080

CMD ["java", "-jar", "shipping.jar"]